### ISSUE TITLE
Surviving open-source blog post

### ISSUE THREAD

**Issue by balupton** [balupton/meta#5]
Use this issue to discuss the blog post [Surviving open-source](https://medium.com/@balupton/f99b39ceb059)

**Comment by remydagostino** [comment]
I really enjoyed reading what you wrote. I think it represents a struggle than many of us feel.

I think that what we are looking for are ways to build a world where everyone can spend the majority of their time doing things they love. There are so many questions and no bullet proof answers. 

It seems possible to live with very little by working only a few days per week, making up for the reduced income by spending more time finding ways to reduce costs. As I understand you can get your cost of living down pretty low by living like this which maybe ends up giving you a 50-50 split between things we like doing and things we have to do to survive. Is this sustainable though? Does this give us any freedom to live comfortable lives after we lose the ability to work? Does it give us any redundancy against unexpected failures like natural disasters or crippling injury?

I don't know.

I think futurism probably deserves some mention. It's possible that humankind may one achieve post-scarcity - a world where everyone can do what they love because the basic requirements of living are supplied by an automated workforce. If that is possible then we were just born at the wrong time. It may be just our duty to put on our blue, white or khaki shirts build that better world for people just like us in future generations.

**Comment by balupton** [comment]
> I really enjoyed reading what you wrote. I think it represents a struggle than many of us feel.

Thank you. I was really afraid that this would jeopardize my reputation somehow due to the critical nature of it. I'm glad to hear your support.

> It seems possible to live with very little by working only a few days per week, making up for the reduced income by spending more time finding ways to reduce costs. As I understand you can get your cost of living down pretty low by living like this which maybe ends up giving you a 50-50 split between things we like doing and things we have to do to survive. Is this sustainable though? Does this give us any freedom to live comfortable lives after we lose the ability to work? Does it give us any redundancy against unexpected failures like natural disasters or crippling injury?

Yeah definitely an option and vital questions.

For the most part, this is sponsored living is how I spent 2012 and 2013. However in my case, when that sponsor pulls out or you run out of work that aligns with you, you're situation becomes dire as you have no income.

Fortunately, this is at least what Gratipay is trying to solve. Sustainable long-term and distributed money. So that if a few people pull out, it's not all over.

I think an alternative to this is having multiple companies, say 15 companies donate $100/week. Which should be easy enough, and if a few drop out, you're still good, and can replace them.

However, for me at least, it still raises the trap of the cognitive dissonance that money has. Why do we go to work each day? Is this problem really helping the world? Does it help the billions in poverty? Or just helps a few CEOs get richer over an app that really doesn't matter at all in grand scheme of things.

These questions eat away at me... I find them refreshing and inspiring and at least a calling for the urgency of the moneyless initiative. #4 

> I think futurism probably deserves some mention. It's possible that humankind may one achieve post-scarcity - a world where everyone can do what they love because the basic requirements of living are supplied by an automated workforce. If that is possible then we were just born at the wrong time. It may be just our duty to put on our blue, white or khaki shirts build that better world for people just like us in future generations.

These are some great points. I've suspected them also. I've read a lot about post-scarcity. I actually think that there will be an emergent economy of excess, rather than just an economy of scarcity that we have today. I'd like to write about that a lot more, as if the excess is harnessed as well as the scarcity, our problems are solved.

Will read up about futurism. Any good links?

**Comment by remydagostino** [comment]
I think I just made up futurism. When I looked it up I found that it was not what I thought it was! Whoops.

I guess what I was talking about though is just the idea that we have a moral obligation to future generations. I'm not sure if it has a name, but there seem to be some good write ups online, such as [this one](http://global.oup.com/us/companion.websites/9780195332957/student/adtlchapter/pdf/Future_Chapter.pdf)

Some of my friends have just asked their employers to go down to 3 days per week. In many ways this gives a nice balance between selling-out and being free to work on what interests you. It's very reliable since Australian law prevents them from just pulling out on you.

**Comment by ahdinosaur** [comment]
thanks for the great blog post @balupton.

i'm interested in better (moneyless, resilient, productive) dwellings for hackers. :) see also, [hackbases](http://hackerspaces.org/wiki/Hackbase) and [eco-villages](http://www.wikiwand.com/en/Ecovillage).

**Comment by jeffmcneill** [comment]
Living in Thailand the past 5+ years has dramatically lowered my cost-of-living, which has a positive effect insofar as less time is needed to do things for money, and more time can be devoted to creating capital (to further free future time) and doing creative stuff. It doesn't solve the problem (living in lower cost locations which still have International standard amenities), but does have a significant effect. 

Note: the use of github issues as a commenting system is inspiring, thank you for the post and for this commenting system!

**Comment by balupton** [comment]
@ahdinosaur 

> i'm interested in better (moneyless, resilient, productive) dwellings for hackers. :) see also, hackbases and eco-villages.

+1, I've added link to the ecovillages and hackbases to the relevant suggestion in the article :)

@jeffmcneill 

> Living in Thailand the past 5+ years has dramatically lowered my cost-of-living, which has a positive effect insofar as less time is needed to do things for money, and more time can be devoted to creating capital (to further free future time) and doing creative stuff. It doesn't solve the problem (living in lower cost locations which still have International standard amenities), but does have a significant effect.

yeah, big +1 too. This was my original goal with Startup Hostel, to make such a lifestyle more accessible to people, without having to abandon your community. Alas to say, progress on that front has been slow — as a tourist to those areas, it's hard to set such things up, nor is it particularly something that I enjoy it turns out after spending 6 weeks in Bali on such an initiative. The real problem isn't so much finding a place, but marketing it, and then getting people to come at the right time. However, things like startupworkaway.com do fine on this front, so maybe it's just a skill I'm missing.

I'd like to see more things such as that appear. @elf-pavlik is doing a great job of this in Spain and Germany with his unMonastery work.

Regardless, I'd love to learn more about your experience with Thailand. It's an area that I've evaluated heavily, and have set as one of the options for permanent living.

> thanks for the great blog post @balupton.
> 
> Note: the use of github issues as a commenting system is inspiring, thank you for the post and for this commenting system!

Thanks :)

**Comment by jeffmcneill** [comment]
Just ran across the licensing of Birdfont, an open source product, very interesting as it has licensing and pricing variety: http://birdfont.org/download.php

**Comment by balupton** [comment]
@jeffmcneill very very cool

**Comment by egasimus** [comment]
Personal observation: one who views the human condition through the post-post-modern perspectives inevitably arising by mere observation of life in the information age tends to see all questions of social organization decompose into fundamentally irresolvable questions of existentialism rather quickly. (Though a decade's practice in the practical manipulation of abstract objects also helps.) Fallacious Facebook flamewars propagating the memetic phenotype of somebody's misguided ideas about the society of tomorrow become alienating rather than infuriating as the notion of "self-governance" effortlessly decomposes into the "what is self" and "what is [control](http://seansturm.wordpress.com/2010/09/21/burroughs-on-how-to-escape-the-society-of-control/)" that come to mind at least once a day, more often if bad things happen to you.

Living in a time of lightspeed communication means that individuals inclined towards intentionally increasing self-awareness are bound to bump against the limits of their own individualities more often than ever before, and, with greater control of behavioral feedback loops, perceive that in much clearer definition than those great thinkers of times past that were sadly bound by one aspect of their culture or another. Consider [solipsism](http://en.wikipedia.org/wiki/Solipsism) -- this little philosophical gem which dates at least as far back as [Plato](http://www.smbc-comics.com/?id=3110), and is only coming to bear fruit (in the form of practical implication) today, in an age when the hunger for experiences is so easily satiated, and the flaws of mass modern man ever more exposed by making available that coveted instant gratification that we've been programmed to seek all along.

There's an upcoming resurgence of psychedelic culture in the West -- a response to that mass reaching of the limits of one's consciousness as well as part of something larger that I can't put my finger on yet -- but how to survive a bad shroom trip is hardly the only thing that we can learn from the experiences of the people who lived in the previous period of perceived enlightenment. For example, here's a handy reference to the [8-circuit model of consciousness](http://www.phinnweb.org/neuro/8-circuit/winnerloser.html). The 8-circuit model is this pile of pseudoscientific hippie mumbo jumbo that our 1960's equivalents came up with, and while it might not hold up to scientific scrutiny, I find that it does tie some things together quite nicely, which is about as much as you can say for any unit of information that happens to reside in your mind at any point.

On that list, I find myself as a seventh circuit winner and loser simultaneously. I have come to feel the deep, subliminal connections between the fate of the individual and the epochal processes, tendencies, and systems that outlive any person; the intangible life of thoughts and concepts as they are subjected to their own evolutionary processes that we are only beginning to notice as ever increasing amounts of information are being processed ever more quickly on this just as tiny as ever speck of dust we call Earth. And yet, one of the basic tenets of evolutionary principles is that evolution could not care less about the individual per se; this magnificent process we all participate in is actually happening on the plane of evolutionary units which are but parts of us -- though, more often than not, you feel different parts of yourself contradict each other.

It is at this point where the question of the self strikes with utmost gravity and simultaneously loses its meaning. You are a human being which is guided by the principles of self-continuation -- just like any other system on any other level of scale in the universe. And yet, you are aware of that; you have a consciousness which is not only capable to understand those principles -- but, what is even more fascinating, capable of being wrong; to put confidence into one mental model of reality which, unbeknownst to them, diverges from what their sensory perceptions would convince them to be objective reality. Human beings tend to make their first errors in early childhood, but are usually conditioned by the natural forces of their environment not to realize the implications of this, and get used to being wrong like it's no big deal. Some children fail to receive the normative conditioning and end up in strange places -- underconditioned ones on the [autism spectrum](http://en.wikipedia.org/wiki/Autism_spectrum), overconditioned ones in the [dark triad](http://en.wikipedia.org/wiki/Dark_triad). Ever try to get into either's shoes? No need to. Simply try to follow the mental patterns of another neurotypical human being, try to get into their head, so to say -- and you'll end up with a headache. Our culture is about being wrong at least as much as it's about being right.

In the end, you do not have the tools to prove that you're not just a [brain in a vat](http://en.wikipedia.org/wiki/Brain_in_a_vat), you can't prove whether reality is a simulation from inside it, you cannot possibly know you're wrong until you're proven wrong, which may very well never happen; yet you have a constant stream of sensory information which even seems to make some sense, but it has also contains the information which made you realize that the information only makes sense because your entire consciousness has been constructed around it and by it, things like knowing you're lying to yourself about so many things, and knowing that the long-kept secret that everybody is lying to oneself a whole lot, the very same secret which made religion happen, has now gotten out and its public knowledge is rapidly permeating collective consciousness ever since at least Freud, thus making it clear that you know that you're not letting yourself know that you're lying to yourself -- stuck inside all of this, [how do you know](http://www.smbc-comics.com/comics/20100522after.gif) you're not wrong even about your very introspection?

This is the door that solipsism opens. The whole notion of 'self', while biologically hardcoded, socially established and harshly enforced by physical realities, begins to dissolve. You are but part of the bigger things and but a container to the smaller ones, and you have no special place in the universe. I suspect that configuring that tiresome analog biocomputer between one's ears to not perceive people as some sort of atomic monads, but as products of circumstances, representations of principles, sums of parts and parts of the whole -- the same way as one rationally analyzes all the non-personified events of life -- is the key to being sincerely understanding and compassionate, and having a net positive effect on others. Perhaps it is the road to what, in less defined times, was called "wisdom". Or perhaps I'm just looking for a way to finally stop writing this :-)

I apologize if this has seemed vastly far-fetched. I may have read in the original article a thing or two that weren't actually there. But I was delighted to see someone touch on the more humane side of the subject of our ways of life so I decided to add my two cents. Consider it a frame of reference, if you like. An overly detailed description of the backdrop against which we are trying to structure our lives in such a way that they make more sense _to us_, which is what Ben's article was about in the first place.

But then again, I can't ever know how much of what I've said is reflecting a more general pattern that can be referenced against, and how much of it is specific to my own mental model of reality, though frankly I'd love to hear your thoughts on the matter.

**Comment by balupton** [comment]
@egasimus bravo

I'll do my reading on your resources and formulate a response when the time is right. For what it's worth, the general pattern is one that I see to. Humans thrive on purpose, the problem with purpose is that it is largely, if not entirely, subjective.

**Comment by ahdinosaur** [comment]
@egasimus :)

**Comment by s-oram** [comment]
Thanks for writing the article. It's comforting to know somebody else is thinking about these things. 

The three choices (support the system, live moneyless, suicide/give-up) are not exclusive. We can compromise to find somewhere to exist in between the extremes. It won't make the question go away but hopefully make our days a little better overall. 

> In the end, you do not have the tools to prove that you're not just a brain in a vat, you can't prove whether reality is a simulation from inside it

Some physicists are searching for evidence. But I don't have the background to follow their theories so can't tell if they're wacky or not. 

> It's possible that humankind may one achieve post-scarcity [...] If that is possible then we were just born at the wrong time. It may be just our duty to put on our blue, white or khaki shirts build that better world for people just like us in future generations.

It would be much easier to do our _duty_ if the earth wasn't quickly heading towards ecological catastrophe. Humanity won't reach a post-scarcity society in a 2+ degree world. Personally, I think we have the technological means to limit global warming but not the cultural will power. We don't seem to have the ability to shift away from growth-at-all-costs economic systems. **We can't have infinite growth on a finite planet.** 

I've read a few interesting articles on why we're having so much trouble combating global warming. The articles discuss why groups of people are resistant to change and so on. I can't find the articles now but will look some more if you're interested. 

If improving the world for future generations is the goal, I suggest our _duty_ is to seek change now. Continuing along the business as usual trend we're on, the earth will likely reach 2 degrees warming around 2036. http://www.scientificamerican.com/sciam/assets/Image/articles/earth-will-cross-the-climate-danger-threshold-by-2036_large.jpg 2 degress of warming is not good.

**Comment by balupton** [comment]
@s-oram thanks for the post, interesting notions. I've found Peter Russell's book "Waking Up in Time" to be a great complement to the points you've raised, luckily it provides a lot of positivity by looking at the universe's ever increasing entropy, and how history, humans, and spirituality have always improved from it (despite at the time, it seeming like it isn't) — so if history is an indicator, then we should be fine, as there doesn't appear to be any society that hasn't believed it wasn't on the verge of ecological/societal despair. 

Having spent 2014 and 2015 moneyless, and now understanding money is for managing scarcity, I think there are options for us. Elon Musk, the first world's commitment to electric vehicles, the growing vegan environmental movement, are all inspiring signs for me.

There certainly are serious issues, and most people don't handle higher entropies than what they grew up with, with that much grace... if any grace... Luckily, it seems people come around... eventually... even if they aren't coming around for the right reasons.

**Comment by balupton** [comment]
> I've read a few interesting articles on why we're having so much trouble combating global warming. The articles discuss why groups of people are resistant to change and so on. I can't find the articles now but will look some more if you're interested.

Definitely interested.

**Comment by s-oram** [comment]
Thanks for the book recommendation. I'll check that out. 

> I think there are options for us.

I do agree. There are lots of good things happening that inspire hope. I think the good aspects of humanity will win out given enough time. I just hope we have enough time!

One research paper kind of in the direction I was hinting at:
Testing Theories of American Politics: Elites, Interest Groups, and Average Citizens
http://scholar.princeton.edu/sites/default/files/mgilens/files/gilens_and_page_2014_-testing_theories_of_american_politics.doc.pdf

There are a few articles on New Matida that might be of interest. 
https://newmatilda.com/users/lissa-j

I can't find the actual ones I'm thinking of right now. I'll have to do some more hunting later.

**Comment by balupton** [comment]
Post is live, so people can discuss it as medium responses
